Script for teamcity tests checking
ablab/stringdecomposer pull request #8
Opened 2020-09-25 15:18 UTC by olga24912

2020-09-25 18:36 UTC, seryrzu requested changes

2020-09-25 18:36 UTC, seryrzu commented on sd/test/teamcity.py
> +class Log:
is this the log class that is expected to be used everywhere in the project? We already have a logger here: https://github.com/ablab/stringdecomposer/blob/devel/sd/standard_logger.py
Can you please merge them?

2020-09-25 18:36 UTC, seryrzu commented on sd/test/teamcity.py
> +    def warn(self, s):
I believe python already provides logger levels. Please see logging.INFO etc

2020-09-25 18:36 UTC, seryrzu commented on sd/test/teamcity.py
> +class Log:
Example of usage: https://github.com/ablab/stringdecomposer/blob/api/sd/cluster_sequences.py

2020-09-28 07:34 UTC, TanyaDvorkina reviewed
Looks Ok for me. Let's merge after addressing Andrey's comments.

2021-07-21 05:05 UTC, seryrzu commented
This PR became obsolete. CI is currently implemented via GitHub actions.

2021-07-21 05:05 UTC, closed without merging

2021-07-21 07:14 UTC, asl commented
Please note that we're only having 2000 runtime minutes for action per month for the whole `ablab` organization.